#ifndef SJIT_CONFIG_H
#define SJIT_CONFIG_H

#define SJIT_MAX_LOCALS 256
#define SJIT_MAX_STACK 256
#define SJIT_MAX_PARAMS 64
#define SJIT_MAX_PROCEDURE_CALL_DEPTH 16384
#define SJIT_MAX_LOOP_STATES 2048
#define SJIT_MAX_SCHEDULER_PASSES 100000
#define SJIT_LIST_ITEM_LIMIT 200000
#define SJIT_INITIAL_CAPACITY 8
#define SJIT_WARP_TIME_MS 500.0

#endif
